# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detection.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CommunityDetection(object):
    def setupUi(self, CommunityDetection):
        CommunityDetection.setObjectName("CommunityDetection")
        CommunityDetection.resize(1098, 632)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(CommunityDetection)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(CommunityDetection)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelInputNetwork = QtWidgets.QLabel(self.groupBox)
        self.labelInputNetwork.setObjectName("labelInputNetwork")
        self.horizontalLayout.addWidget(self.labelInputNetwork)
        self.comboBoxInputNetwork = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxInputNetwork.setObjectName("comboBoxInputNetwork")
        self.comboBoxInputNetwork.addItem("")
        self.comboBoxInputNetwork.addItem("")
        self.comboBoxInputNetwork.addItem("")
        self.comboBoxInputNetwork.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxInputNetwork)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelInputAlgorithm = QtWidgets.QLabel(self.groupBox)
        self.labelInputAlgorithm.setObjectName("labelInputAlgorithm")
        self.horizontalLayout_2.addWidget(self.labelInputAlgorithm)
        self.comboBoxInputAlgorithm = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxInputAlgorithm.setObjectName("comboBoxInputAlgorithm")
        self.comboBoxInputAlgorithm.addItem("")
        self.comboBoxInputAlgorithm.addItem("")
        self.comboBoxInputAlgorithm.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxInputAlgorithm)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelInputParameters = QtWidgets.QLabel(self.groupBox)
        self.labelInputParameters.setObjectName("labelInputParameters")
        self.horizontalLayout_6.addWidget(self.labelInputParameters)
        self.lineEditParameters = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditParameters.setReadOnly(False)
        self.lineEditParameters.setObjectName("lineEditParameters")
        self.horizontalLayout_6.addWidget(self.lineEditParameters)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowserResult = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowserResult.setObjectName("textBrowserResult")
        self.verticalLayout_3.addWidget(self.textBrowserResult)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonSubmit = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSubmit.sizePolicy().hasHeightForWidth())
        self.buttonSubmit.setSizePolicy(sizePolicy)
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.horizontalLayout_5.addWidget(self.buttonSubmit)
        self.buttonExit = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonExit.sizePolicy().hasHeightForWidth())
        self.buttonExit.setSizePolicy(sizePolicy)
        self.buttonExit.setObjectName("buttonExit")
        self.horizontalLayout_5.addWidget(self.buttonExit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelMeasure = QtWidgets.QLabel(self.groupBox_7)
        self.labelMeasure.setObjectName("labelMeasure")
        self.horizontalLayout_7.addWidget(self.labelMeasure)
        self.comboBoxMeasure = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBoxMeasure.setObjectName("comboBoxMeasure")
        self.comboBoxMeasure.addItem("")
        self.comboBoxMeasure.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxMeasure)
        spacerItem = QtWidgets.QSpacerItem(283, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.buttonConfirm = QtWidgets.QPushButton(self.groupBox_7)
        self.buttonConfirm.setObjectName("buttonConfirm")
        self.horizontalLayout_7.addWidget(self.buttonConfirm)
        self.horizontalLayout_7.setStretch(0, 3)
        self.horizontalLayout_7.setStretch(1, 4)
        self.horizontalLayout_7.setStretch(2, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelInputParameters2 = QtWidgets.QLabel(self.groupBox_7)
        self.labelInputParameters2.setObjectName("labelInputParameters2")
        self.horizontalLayout_9.addWidget(self.labelInputParameters2)
        self.lineEditParameters2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEditParameters2.setObjectName("lineEditParameters2")
        self.horizontalLayout_9.addWidget(self.lineEditParameters2)
        spacerItem1 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(1, 4)
        self.horizontalLayout_9.setStretch(3, 5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidgetCompareResult = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidgetCompareResult.setObjectName("tableWidgetCompareResult")
        self.tableWidgetCompareResult.setColumnCount(3)
        self.tableWidgetCompareResult.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompareResult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompareResult.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompareResult.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompareResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompareResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompareResult.setHorizontalHeaderItem(2, item)
        self.tableWidgetCompareResult.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCompareResult.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tableWidgetCompareResult)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(CommunityDetection)
        self.tabWidget.setCurrentIndex(0)
        self.buttonSubmit.clicked.connect(CommunityDetection.submit_alog)
        self.buttonExit.clicked.connect(CommunityDetection.exit_alog)
        self.buttonConfirm.clicked.connect(CommunityDetection.plot_metrics_graph)
        QtCore.QMetaObject.connectSlotsByName(CommunityDetection)

    def retranslateUi(self, CommunityDetection):
        _translate = QtCore.QCoreApplication.translate
        CommunityDetection.setWindowTitle(_translate("CommunityDetection", "Form"))
        self.groupBox.setTitle(_translate("CommunityDetection", "输入数据："))
        self.labelInputNetwork.setText(_translate("CommunityDetection", "输入网络："))
        self.comboBoxInputNetwork.setItemText(0, _translate("CommunityDetection", "Karata_Network"))
        self.comboBoxInputNetwork.setItemText(1, _translate("CommunityDetection", "Dolphin_Network"))
        self.comboBoxInputNetwork.setItemText(2, _translate("CommunityDetection", "football_Network"))
        self.comboBoxInputNetwork.setItemText(3, _translate("CommunityDetection", "cond-mat_Network"))
        self.labelInputAlgorithm.setText(_translate("CommunityDetection", "输入算法："))
        self.comboBoxInputAlgorithm.setItemText(0, _translate("CommunityDetection", "LPA"))
        self.comboBoxInputAlgorithm.setItemText(1, _translate("CommunityDetection", "Louvain"))
        self.comboBoxInputAlgorithm.setItemText(2, _translate("CommunityDetection", "GN"))
        self.labelInputParameters.setText(_translate("CommunityDetection", "输入参数（社团个数）："))
        self.groupBox_2.setTitle(_translate("CommunityDetection", "社区划分结果："))
        self.groupBox_4.setTitle(_translate("CommunityDetection", "真实网络展示"))
        self.groupBox_3.setTitle(_translate("CommunityDetection", "社区划分结果图展示"))
        self.buttonSubmit.setText(_translate("CommunityDetection", "提交"))
        self.buttonExit.setText(_translate("CommunityDetection", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CommunityDetection", "社区检测算法"))
        self.labelMeasure.setText(_translate("CommunityDetection", "度量指标："))
        self.comboBoxMeasure.setItemText(0, _translate("CommunityDetection", "Modularity"))
        self.comboBoxMeasure.setItemText(1, _translate("CommunityDetection", "NMI"))
        self.buttonConfirm.setText(_translate("CommunityDetection", "确定"))
        self.labelInputParameters2.setText(_translate("CommunityDetection", "输入参数："))
        self.groupBox_5.setTitle(_translate("CommunityDetection", "比较结果图"))
        self.groupBox_6.setTitle(_translate("CommunityDetection", "比较结果表"))
        item = self.tableWidgetCompareResult.verticalHeaderItem(0)
        item.setText(_translate("CommunityDetection", "karata"))
        item = self.tableWidgetCompareResult.verticalHeaderItem(1)
        item.setText(_translate("CommunityDetection", "football"))
        item = self.tableWidgetCompareResult.verticalHeaderItem(2)
        item.setText(_translate("CommunityDetection", "dolphin"))
        item = self.tableWidgetCompareResult.horizontalHeaderItem(0)
        item.setText(_translate("CommunityDetection", "LPA"))
        item = self.tableWidgetCompareResult.horizontalHeaderItem(1)
        item.setText(_translate("CommunityDetection", "GN"))
        item = self.tableWidgetCompareResult.horizontalHeaderItem(2)
        item.setText(_translate("CommunityDetection", "Louvain"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CommunityDetection", "算法比较"))

